export const createNewImageElement = (src) => ({
  id: `img_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
  type: 'image',
  src,
  visible: true,
  rotation: 0,
  zIndex: 1,
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  crop: null,
  filters: { brightness: 100, contrast: 100, saturate: 100, blur: 0, opacity: 100 },
  shadow: false,
  shadowColor: '#000000',
  shadowBlur: 10,
  shadowOffsetX: 5,
  shadowOffsetY: 5,
  borderColor: '#000000',
  borderWidth: 0,
  borderRadius: 0,
});
